version: '3'
services:
  postgres:
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: tpch
    volumes:
      - ./csvs/:/data/:ro
      - ./tpch-dbgen/dss.ddl:/docker-entrypoint-initdb.d/01_create_tables.sql:ro
      - ./populate_tables.sql:/docker-entrypoint-initdb.d/02_populate_tables.sql:ro
      - ./postgres-data:/var/lib/postgresql/data
